# Generated by Django 3.2.15 on 2023-10-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20231022_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burgercount',
            name='product',
        ),
        migrations.AddField(
            model_name='burgercount',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
