# Generated by Django 3.2.15 on 2023-10-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20231022_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BurgerCount',
            new_name='OrderElements',
        ),
    ]
