# Generated by Django 3.2.15 on 2023-11-10 05:41

import django.db.models.deletion
from django.db import migrations, models


def remove_products(apps, _):
    OrderElement = apps.get_model("foodcartapp", "OrderElement")
    OrderElement.objects.filter(product=111).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0047_alter_orderelement_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                    to='foodcartapp.product', verbose_name='Товар'),
        ),
        migrations.RunPython(remove_products)
    ]
