# Generated by Django 3.2.15 on 2023-11-10 05:46

import builtins

import django.core.validators
from django.db import migrations, models
from django.db.models import F, Sum


def fill_in_unspecified_prices(apps, _):
    OrderElement = apps.get_model("foodcartapp", "OrderElement")
    elements = OrderElement.objects.select_related('product')
    for element in elements.iterator():
        element.price = element.product.price * element.quantity
        element.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0048_alter_orderelement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8,
                                      validators=[django.core.validators.MinValueValidator(0)],
                                      verbose_name='Цена заказа', default=0),
            preserve_default=False,
        ),
        migrations.RunPython(fill_in_unspecified_prices),
        migrations.AlterField(
            model_name='orderelement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8,
                                      validators=[django.core.validators.MinValueValidator(0)],
                                      verbose_name='Цена заказа'),
            preserve_default=False,
        ),
    ]
