# Generated by Django 3.2.15 on 2023-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_orderelement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('M', 'Передан менеджеру'), ('R', 'Передан ресторану'), ('C', 'Передан курьеру'), ('P', 'Обработанный')], db_index=True, default='M', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
