# Generated by Django 3.2.15 on 2023-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20231111_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('C', 'Наличные'), ('N', 'Безналичные')], db_index=True, default='C', max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
